version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: ./docker/images/fpm.dockerfile
    platform: linux/amd64
    image: begaming
    container_name: begaming-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - begaming

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: begaming-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    networks:
      - begaming

  nginx:
    image: nginx:1.19
    tty: true
    container_name: begaming-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/config/nginx/:/etc/nginx/conf.d/
    networks:
      - begaming

  webpack:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: ./docker/images/nodejs.dockerfile
    tty: true
    container_name: begaming-webpack
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - begaming

networks:
  begaming:
    driver: bridge